# Generated by Django 5.2.17 on 2026-09-08 04:11

from typing import Any

from django.db import migrations, models


def map_existing_staff_to_admin(apps: Any, schema_editor: Any) -> None:
    user_model = apps.get_model("identity", "User")
    user_model.objects.filter(is_staff=True).update(role="ADMIN")


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='STUDENT', max_length=16),
        ),
        migrations.RunPython(map_existing_staff_to_admin, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_staff', True), ('role', 'ADMIN')), models.Q(('is_staff', False), ('role', 'STUDENT')), _connector='OR'), name='identity_role_matches_staff'),
        ),
    ]
