# Generated by Django 5.2.17 on 2026-09-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_user_options_alter_user_email_telegramidentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerificationThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_digest', models.CharField(max_length=64, unique=True)),
                ('window_started_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('window_started_at',),
            },
        ),
    ]
