# Generated by Django 5.2.17 on 2026-09-08 05:39

from typing import Any

from django.db import migrations, models


def classify_existing_updates(apps: Any, schema_editor: Any) -> None:
    TelegramUpdate = apps.get_model("identity", "TelegramUpdate")
    TelegramUpdate.objects.filter(login_code__isnull=False).update(response_kind="CODE")
    TelegramUpdate.objects.filter(login_code__isnull=True).update(response_kind="COOLDOWN")


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_telegramverificationthrottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramidentity',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='telegramupdate',
            name='response_kind',
            field=models.CharField(choices=[('CONTACT_PROMPT', 'Contact prompt'), ('CODE', 'Login code'), ('COOLDOWN', 'Cooldown')], default='CONTACT_PROMPT', max_length=16),
        ),
        migrations.RunPython(classify_existing_updates, migrations.RunPython.noop),
    ]
