# Generated by Django 5.2.17 on 2026-09-08 05:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_telegramidentity_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDeviceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_id', models.UUIDField()),
                ('device_name', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='identity_one_session_per_device')],
            },
        ),
    ]
