# Generated by Django 5.2.17 on 2026-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_unique_telegram_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_digest', models.CharField(max_length=64, unique=True)),
                ('window_started_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('window_started_at',),
            },
        ),
        migrations.RemoveField(
            model_name='authdevicesession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='telegramidentity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='telegramlogincode',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='telegramupdate',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='telegramupdate',
            name='login_code',
        ),
        migrations.DeleteModel(
            name='TelegramVerificationThrottle',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='AuthDeviceSession',
        ),
        migrations.DeleteModel(
            name='TelegramIdentity',
        ),
        migrations.DeleteModel(
            name='TelegramLoginCode',
        ),
        migrations.DeleteModel(
            name='TelegramUpdate',
        ),
    ]
