# Generated by Django 5.2.17 on 2026-09-11 15:28

import django.core.validators
import django.db.models.deletion
import neoskill.identity.models
import secrets
from django.conf import settings
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def populate_referral_codes(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    user_model = apps.get_model('identity', 'User')
    alphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"
    used = set(user_model.objects.exclude(referral_code__isnull=True).values_list('referral_code', flat=True))
    for user in user_model.objects.filter(referral_code__isnull=True).iterator():
        code = "".join(secrets.choice(alphabet) for _ in range(12))
        while code in used:
            code = "".join(secrets.choice(alphabet) for _ in range(12))
        user_model.objects.filter(pk=user.pk).update(referral_code=code)
        used.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0009_devicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(editable=False, max_length=12, null=True),
        ),
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=neoskill.identity.models.generate_referral_code, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_discount_applied',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_discount_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('referral_discount_percent__lte', 100)), name='identity_referral_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('referral_discount_applied__lte', 100)), name='identity_referral_discount_applied_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('referred_by')), _negated=True), name='identity_referral_no_self_reference'),
        ),
    ]
