# Generated by Django 5.2.17 on 2026-09-11 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='NeoSkill', max_length=100)),
                ('footer_text', models.CharField(default='O‘rganing. Amalda bajaring. Natijaga erishing.', max_length=300)),
                ('company_name', models.CharField(default='NeoSkill', max_length=200)),
                ('about_title', models.CharField(default='Ta’limni aniq yo‘l va amaliy natijaga aylantiramiz', max_length=200)),
                ('about_text', models.TextField(default='NeoSkill — zamonaviy kasblarni izchil o‘rganish platformasi.')),
                ('company_address', models.CharField(blank=True, max_length=500)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_telegram', models.CharField(blank=True, max_length=100)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('smtp_source', models.CharField(choices=[('ENV', 'Environment'), ('ADMIN', 'Admin')], default='ENV', max_length=12)),
                ('smtp_host', models.CharField(blank=True, max_length=253)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=254)),
                ('smtp_password_encrypted', models.TextField(blank=True)),
                ('smtp_security', models.CharField(choices=[('TLS', 'STARTTLS'), ('SSL', 'SSL/TLS'), ('NONE', 'None')], default='TLS', max_length=12)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='platform_settings_singleton')],
            },
        ),
    ]
