'use client';
import Link from 'next/link';
import { useState } from 'react';
import type { LearningNavigation, MyCourse } from '@/lib/types';
import { CourseVisual } from './Public';
import { Badge, ProgressBar, StatusBadge } from '@/components/ui';

export function StudentCourseCard({ enrollment }: { enrollment: MyCourse }) { return <article className="ns-student-course"><CourseVisual title={enrollment.course.title} compact imageUrl={enrollment.course.image_url}/><div><Badge tone="brand">{enrollment.course.category?.name}</Badge><h2>{enrollment.course.title}</h2><p>{enrollment.course.instructor?.name}</p><ProgressBar value={enrollment.progress.percent} label={`${enrollment.progress.completed_units}/${enrollment.progress.required_units} bosqich`}/><Link className="ns-link-button" href={`/learn/${enrollment.course.slug}`}>O‘qishni davom ettirish</Link></div></article> }

export function LearningSidebar({ navigation, courseSlug, currentLesson }: { navigation: LearningNavigation; courseSlug: string; currentLesson?: string | undefined }) { const [open,setOpen]=useState(false); return <><button type="button" className="ns-learning-toggle" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>Kurs tarkibi <span>☰</span></button><aside className="ns-learning-sidebar" data-open={open||undefined}><header><Link href="/my-courses">← Kurslarim</Link><h1>{navigation.title}</h1><ProgressBar value={navigation.progress.percent}/></header><nav aria-label="Kurs tarkibi">{navigation.modules.map(module=><details key={module.id} open><summary>{module.position}-modul. {module.title}</summary>{module.topics.map(topic=><section key={topic.id} data-locked={topic.is_locked||undefined}><h2>{topic.title}{topic.is_locked?<span>Yopiq</span>:null}</h2>{topic.lessons.map(item=>item.is_locked?<span className="ns-lesson-link" key={item.id} data-status="locked"><i>◌</i>{item.title}</span>:<Link className="ns-lesson-link" key={item.id} data-active={currentLesson===item.id||undefined} data-status={item.is_completed?'completed':'available'} href={`/learn/${courseSlug}/lesson/${item.id}`}><i>{item.is_completed?'✓':'▶'}</i>{item.title}</Link>)}{topic.practice&&topic.lessons.at(-1)?<Link className="ns-lesson-link" href={`/learn/${courseSlug}/lesson/${topic.lessons.at(-1)!.id}#practice`}><i>{topic.practice.is_completed?'✓':'◇'}</i>Amaliy topshiriq</Link>:null}{topic.test?(topic.test.status==='LOCKED'?<span className="ns-lesson-link" data-status="locked"><i>?</i>Mavzu testi <StatusBadge status={topic.test.status}/></span>:<Link className="ns-lesson-link" href={`/learn/${courseSlug}/test/${topic.id}`}><i>?</i>Mavzu testi <StatusBadge status={topic.test.status}/></Link>):null}</section>)}</details>)}</nav></aside></> }
