import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('production data mode defaults to API and mutations keep CSRF credentials', async()=>{const source=await readFile('src/lib/api.ts','utf8');assert.match(source,/NODE_ENV === 'development'/);assert.match(source,/credentials: 'include'/);assert.match(source,/X-CSRFToken/)});
test('forbidden MVP controls are absent from product UI',async()=>{const files=['src/components/screens/public/HomeScreen.tsx','src/components/screens/public/CoursesScreen.tsx','src/components/screens/public/CourseDetailScreen.tsx','src/components/screens/auth/PasswordAuthScreens.tsx'];const source=(await Promise.all(files.map(file=>readFile(file,'utf8')))).join('\n').toLowerCase();for(const forbidden of ['google sign-in','payme','click payment','★'])assert.equal(source.includes(forbidden),false,forbidden)});
test('critical persisted actions call the API adapter',async()=>{const source=await readFile('src/components/screens/student/LearningScreens.tsx','utf8');for(const call of ['api.completeLesson','api.completePractice','api.submitTest'])assert.ok(source.includes(call),call);const auth=await readFile('src/components/screens/auth/PasswordAuthScreens.tsx','utf8');for(const call of ['api.login','api.register','api.requestPasswordReset','api.confirmPasswordReset'])assert.ok(auth.includes(call),call)});

test('admin settings and statistic details use real API persistence',async()=>{const api=await readFile('src/lib/api.ts','utf8');for(const route of ['/settings/public','/admin/settings','/admin/settings/test-email','/admin/statistics/enrollments','/admin/statistics/attempts'])assert.ok(api.includes(route),route);const settings=await readFile('src/components/screens/admin/SettingsScreen.tsx','utf8');for(const call of ['api.adminSettings','api.saveSettings','api.testEmail'])assert.ok(settings.includes(call),call);const stats=await readFile('src/components/screens/admin/StatisticsScreen.tsx','utf8');for(const call of ['api.adminEnrollmentStats','api.adminAttemptStats'])assert.ok(stats.includes(call),call)});

test('catalog follows every API page and logout failures remain visible',async()=>{const api=await readFile('src/lib/api.ts','utf8');assert.match(api,/while \(next\)/);assert.match(api,/page\.results/);assert.match(api,/pagination limit exceeded/);assert.match(api,/reason instanceof TypeError.*return fallback/);const session=await readFile('src/lib/session.ts','utf8');assert.doesNotMatch(session,/api\.logout\(\);\s*}\s*catch\s*{\s*\/\*/);const shell=await readFile('src/components/layout/Shells.tsx','utf8');assert.match(shell,/Tizimdan chiqib bo‘lmadi/);assert.match(shell,/role="alert"/)});

test('an empty NEXT_PUBLIC_API_URL still falls back to the same-origin proxy path',async()=>{const source=await readFile('src/lib/api.ts','utf8');
  // `??` would keep an empty build arg and send every request to a relative path with no prefix.
  assert.match(source,/NEXT_PUBLIC_API_URL\?\.trim\(\)\s*\|\|\s*'\/api\/v1'/);
  assert.doesNotMatch(source,/NEXT_PUBLIC_API_URL\s*\?\?/)});

test('referral attribution survives navigation and admin discount actions use the API',async()=>{const api=await readFile('src/lib/api.ts','utf8');for(const route of ['/referrals/','/me/referral','/admin/referrals'])assert.ok(api.includes(route),route);const capture=await readFile('src/lib/referral.tsx','utf8');assert.match(capture,/localStorage\.setItem/);assert.match(capture,/neoskill-referral-code/);const auth=await readFile('src/components/screens/auth/PasswordAuthScreens.tsx','utf8');assert.match(auth,/referral_code/);assert.match(auth,/forgetReferralCode/);const admin=await readFile('src/components/screens/admin/ReferralScreen.tsx','utf8');for(const call of ['api.adminReferrals','api.adminReferral','api.adminReferralDiscount'])assert.ok(admin.includes(call),call)});

test('public metadata and sitemap use production course data',async()=>{const layout=await readFile('src/app/layout.tsx','utf8');assert.match(layout,/metadataBase/);assert.match(layout,/openGraph/);const detail=await readFile('src/app/courses/[slug]/page.tsx','utf8');assert.match(detail,/generateMetadata/);assert.match(detail,/short_description/);assert.match(detail,/alternates/);const sitemap=await readFile('src/app/sitemap.ts','utf8');assert.doesNotMatch(sitemap,/fixtures/);assert.match(sitemap,/BACKEND_INTERNAL_URL/);assert.match(sitemap,/force-dynamic/)});

test('production home loads all marketing sections from public APIs',async()=>{const api=await readFile('src/lib/api.ts','utf8');for(const route of ["'/categories'","'/instructors'","'/testimonials'"])assert.ok(api.includes(route),route);const home=await readFile('src/components/screens/public/HomeScreen.tsx','utf8');assert.match(home,/api\.home\(\)/);assert.match(home,/ns-category-grid/);assert.match(home,/testimonials\.map/);assert.doesNotMatch(home,/Telegram orqali xavfsiz kiring/)});

test('course CTA trusts the API enrollment state in production',async()=>{const types=await readFile('src/lib/types.ts','utf8');assert.match(types,/enrollment_state: EnrollmentState/);assert.doesNotMatch(types,/enrollment_state\?:/);const screen=await readFile('src/components/screens/public/CourseDetailScreen.tsx','utf8');assert.match(screen,/enrollmentState=previewState \?\? course\.enrollment_state/);assert.doesNotMatch(screen,/course\.is_free\?'FREE_START':'PAID_REQUEST'/)});

test('design-preview query switches cannot replace production state',async()=>{const [courses,detail,dashboard,myCourses,learning]=await Promise.all(['src/components/screens/public/CoursesScreen.tsx','src/components/screens/public/CourseDetailScreen.tsx','src/components/screens/student/DashboardScreen.tsx','src/components/screens/student/MyCoursesScreen.tsx','src/components/screens/student/LearningScreens.tsx'].map(file=>readFile(file,'utf8')));assert.match(courses,/ui=useMockData \? params\.get\('ui'\) : null/);assert.match(detail,/previewState=useMockData&&allowed\.includes/);assert.match(dashboard,/empty=useMockData&&search\.get\('empty'\)/);assert.match(dashboard,/pending=useMockData&&search\.get\('pending'\)/);assert.match(myCourses,/empty=useMockData&&search\.get\('empty'\)/);assert.match(learning,/denied = useMockData && search\.get\('access'\)/)});
