# Generated by Django 5.2.17 on 2026-09-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='social_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
