# Generated by Django 5.2.17 on 2026-09-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_instructor_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
