# Generated by Django 5.2.17 on 2026-09-09 15:17

import neoskill.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_lesson_material_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, validators=[neoskill.catalog.models.validate_image_reference]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, validators=[neoskill.catalog.models.validate_image_reference]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, validators=[neoskill.catalog.models.validate_image_reference]),
        ),
    ]
