# Generated by Django 5.2.17 on 2026-09-07 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testattemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.testattempt'),
        ),
        migrations.AddField(
            model_name='testattemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='assessment.question'),
        ),
        migrations.AddField(
            model_name='testattemptanswer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='assessment.questionoption'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('test', 'position'), name='assessment_question_position'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='assessment_option_position'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='assessment_one_correct_option'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 4)), name='assessment_option_position_range'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='assessment_attempt_score_range'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('result', 'IN_PROGRESS'), ('score__isnull', True)), models.Q(('completed_at__isnull', False), ('result__in', ('PASSED', 'FAILED')), ('score__isnull', False)), _connector='OR'), name='assessment_attempt_result_state'),
        ),
        migrations.AddConstraint(
            model_name='testattemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='assessment_one_answer_per_question'),
        ),
    ]
