import type { Course, CourseDetail, LearningNavigation, LessonDetail, MyCourse, Practice, Testimonial, TopicTest } from './types';

const category = { id: 'cat-python', name: 'Dasturlash', slug: 'dasturlash' };
const designCategory = { id: 'cat-design', name: 'Dizayn', slug: 'dizayn' };
export const instructors = [
  { name: 'Sardor Karimov', slug: 'sardor-karimov', title: 'Senior Python Developer', photo_url: '', experience: '8 yillik amaliy tajriba', bio: 'Murakkab mavzularni sodda va amaliy misollar orqali tushuntiradigan dasturchi va mentor.' },
  { name: 'Madina Aliyeva', slug: 'madina-aliyeva', title: 'Product Designer', photo_url: '', experience: '6 yillik mahsulot dizayni tajribasi', bio: 'Mahsulot dizayni va foydalanuvchi tajribasi bo‘yicha mutaxassis.' },
];
export const courses: Course[] = [
  { id: 'course-python', title: 'Python: noldan amaliy dasturchigacha', slug: 'python-asoslari', short_description: 'Python asoslarini real loyihalar orqali o‘rganing va mustahkam poydevor yarating.', image_url: '', level: 'BEGINNER', language: 'O‘zbek', duration_minutes: 720, is_free: true, price: '0.00', category, instructor: instructors[0]! },
  { id: 'course-ui', title: 'UI/UX dizayn asoslari', slug: 'ui-ux-asoslari', short_description: 'Tadqiqotdan prototipgacha bo‘lgan to‘liq dizayn jarayonini egallang.', image_url: '', level: 'BEGINNER', language: 'O‘zbek', duration_minutes: 540, is_free: false, price: '490000.00', category: designCategory, instructor: instructors[1]! },
  { id: 'course-django', title: 'Django REST API amaliyoti', slug: 'django-rest-api', short_description: 'Xavfsiz va kengayadigan REST API’larni professional usulda yarating.', image_url: '', level: 'INTERMEDIATE', language: 'O‘zbek', duration_minutes: 660, is_free: false, price: '590000.00', category, instructor: instructors[0]! },
];
const modules = [{ id: 'module-1', title: 'Python bilan tanishuv', position: 1, topics: [{ id: 'topic-1', title: 'Birinchi qadamlar', position: 1, lessons: [
  { id: 'lesson-1', title: 'Python nima va u qayerda ishlatiladi?', position: 1, kind: 'VIDEO' as const, duration_minutes: 12, free_preview: true, access: 'PREVIEW' as const },
  { id: 'lesson-2', title: 'Muhitni sozlash va birinchi dastur', position: 2, kind: 'VIDEO' as const, duration_minutes: 18, free_preview: false, access: 'LOCKED' as const },
] }, { id: 'topic-2', title: 'O‘zgaruvchilar va ma’lumot turlari', position: 2, lessons: [
  { id: 'lesson-3', title: 'Sonlar, matnlar va mantiqiy qiymatlar', position: 1, kind: 'VIDEO' as const, duration_minutes: 24, free_preview: false, access: 'LOCKED' as const },
] }] }, { id: 'module-2', title: 'Amaliy dasturlash', position: 2, topics: [{ id: 'topic-3', title: 'Shartlar va sikllar', position: 1, lessons: [{ id: 'lesson-4', title: 'Murakkab vazifalarni qismlarga ajratish', position: 1, kind: 'TEXT' as const, duration_minutes: 30, free_preview: false, access: 'LOCKED' as const }] }] }];

export const courseDetails: CourseDetail[] = courses.map((course, index) => ({ ...course, description: `${course.title} kursi nazariya, mashq va mavzu testlarini bir oqimda birlashtiradi. Har bir bosqich natijasi saqlanadi va keyingi mavzu bilim mustahkamlangach ochiladi.`, what_you_will_learn: index === 1 ? ['Foydalanuvchi muammosini tahlil qilish', 'Aniq wireframe va prototip yaratish', 'Interfeys qarorlarini asoslash'] : ['Asosiy tushunchalarni ishonch bilan qo‘llash', 'Amaliy masalalarni mustaqil yechish', 'Tartibli va o‘qilishi oson loyiha yaratish', 'Test orqali bilimni tekshirish'], audience: ['Yo‘nalishni endi boshlayotganlar', 'Bilimini amaliyot bilan mustahkamlamoqchi bo‘lganlar', 'Yangi kasbga tizimli o‘tishni rejalayotganlar'], requirements: ['Kompyuterdan foydalanish bo‘yicha boshlang‘ich bilim', 'Haftasiga kamida 4 soat ajratish', 'O‘rganishga tayyorlik'], modules, faqs: [{ id: 'faq-1', question: 'Kursni qancha vaqtda tugataman?', answer: 'O‘z tezligingizda o‘qiysiz. Tavsiya etilgan jadval bo‘yicha 6–8 haftada yakunlash mumkin.', position: 1 }, { id: 'faq-2', question: 'Oldindan tajriba kerakmi?', answer: 'Boshlang‘ich kurs uchun tajriba talab qilinmaydi. Har bir tushuncha noldan izohlanadi.', position: 2 }], enrollment_state: index === 0 ? 'FREE_START' : 'PAID_REQUEST', referral_discount_percent: 0, discounted_price: course.price }));

export const testimonials: Testimonial[] = [{ id: 'testimonial-1', name: 'Aziza Sobirova', profession: 'Junior dasturchi', text: 'Darslarning ketma-ketligi va amaliy topshiriqlar o‘rganishni ancha osonlashtirdi.', active: true, position: 1 }, { id: 'testimonial-2', name: 'Jasur Rahmonov', profession: 'Talaba', text: 'Har mavzudan keyingi test qayerda xato qilayotganimni tushunishga yordam berdi.', active: true, position: 2 }];

export const myCourses: MyCourse[] = [{ id: 'enrollment-1', status: 'ACTIVE', activated_at: '2026-08-28T10:00:00Z', course: courses[0]!, progress: { required_units: 20, completed_units: 9, percent: 45, is_complete: false, current_lesson_id: 'lesson-2' } }, { id: 'enrollment-2', status: 'ACTIVE', activated_at: '2026-08-20T10:00:00Z', course: courses[1]!, progress: { required_units: 16, completed_units: 12, percent: 75, is_complete: false, current_lesson_id: 'lesson-3' } }];

export const learningNavigation: LearningNavigation = { id: courses[0]!.id, title: courses[0]!.title, slug: courses[0]!.slug, progress: myCourses[0]!.progress, modules: [{ id: 'module-1', title: 'Python bilan tanishuv', position: 1, topics: [{ id: 'topic-1', title: 'Birinchi qadamlar', position: 1, is_locked: false, practice: { id: 'practice-1', is_required: true, is_completed: false }, test: { id: 'test-1', status: 'LOCKED' }, lessons: [{ id: 'lesson-1', title: 'Python nima va u qayerda ishlatiladi?', position: 1, is_required: true, is_completed: true, is_locked: false, free_preview: true }, { id: 'lesson-2', title: 'Muhitni sozlash va birinchi dastur', position: 2, is_required: true, is_completed: false, is_locked: false, free_preview: false }] }, { id: 'topic-2', title: 'O‘zgaruvchilar va ma’lumot turlari', position: 2, is_locked: true, practice: null, test: { id: 'test-2', status: 'LOCKED' }, lessons: [{ id: 'lesson-3', title: 'Sonlar, matnlar va mantiqiy qiymatlar', position: 1, is_required: true, is_completed: false, is_locked: true, free_preview: false }] }] }, { id: 'module-2', title: 'Amaliy dasturlash', position: 2, topics: [{ id: 'topic-3', title: 'Shartlar va sikllar', position: 1, is_locked: true, practice: null, test: { id: 'test-3', status: 'LOCKED' }, lessons: [{ id: 'lesson-4', title: 'Murakkab vazifalarni qismlarga ajratish', position: 1, is_required: true, is_completed: false, is_locked: true, free_preview: false }] }] }] };

export const lesson: LessonDetail = { id: 'lesson-2', topic: 'topic-1', topic_title: 'Birinchi qadamlar', course_slug: 'python-asoslari', title: 'Muhitni sozlash va birinchi dastur', position: 2, kind: 'VIDEO', content: 'Bu darsda Python muhitini o‘rnatamiz, loyiha papkasini tayyorlaymiz va birinchi dasturni ishga tushiramiz. Kodni kichik bosqichlarda yozing va har natijani terminalda tekshiring.', video_url: 'https://example.com/video', material_url: 'https://example.com/material', duration_minutes: 18, is_required: true, free_preview: false, is_completed: false };
export const practice: Practice = { id: 'practice-1', topic: 'topic-1', topic_title: 'Birinchi qadamlar', course_slug: 'python-asoslari', instructions: 'Ismingiz va bugungi maqsadingizni ekranga chiqaradigan kichik Python dasturi yozing.', example: 'print("Salom, men Aziza. Bugun Python o‘rganaman!")', resource_url: 'https://docs.python.org/3/tutorial/', is_required: true, is_completed: false };
export const topicTest: TopicTest = { test_id: 'test-1', available: true, required_lessons: 2, completed_required_lessons: 2, passing_score: 70, questions: Array.from({ length: 5 }, (_, index) => ({ id: `question-${index + 1}`, text: index === 0 ? 'Python dasturini ishga tushirish uchun qaysi fayl kengaytmasi ishlatiladi?' : `${index + 1}-savol: berilgan tushunchaga mos javobni tanlang.`, position: index + 1, options: ['.py', '.html', '.css', '.sql'].map((text, optionIndex) => ({ id: `option-${index + 1}-${optionIndex + 1}`, text, position: optionIndex + 1 })) })) };
